BankCheque/Models/Cheque/ChequeVM.cs
namespace BankCheque.Models.Cheque
{
    public class ChequeVM
    {
        public BusinessModels.Cheque ChequeData = new BusinessModels.Cheque();
        public string PageTitle { get; set; }
        public string HelpMessage { get; set; }
        public string SubmitButtonLabel { get; set; }
        public string PayeeNameLabel { get; set; }
        public string ChequeValueLabel { get; set; }

    }
}

BankCheque/Controllers/ChequeController.cs
using System.Web.Mvc;
using BankCheque.Models.Cheque;
using BankCheque.BusinessModels;
namespace BankCheque.Controllers
{
    public class ChequeController : Controller
    {
        [HttpGet]
        public ActionResult CollectChequeData()
        {
            return View("~/Views/Cheque/ChequeDataCollection.cshtml", new ChequeVM()
            {
                PageTitle = "Create a Bank Cheque",
                HelpMessage = "Cheque details",
                ChequeValueLabel = "Cheque Value",
                PayeeNameLabel = "Payee Name",
                SubmitButtonLabel = "Submit"
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult SubmitCheque(Cheque cheque)
        {
            cheque.ValidateChequeParameters();

            // Do Some back end operations

            return View("~/Views/Cheque/SubmittedCheque.cshtml", new ChequeVM()
            {
                PageTitle = "Bank Cheque",
                ChequeData = new Cheque()
                {
                    PayeeName = cheque.PayeeName,
                    ChequeValueDollars = cheque.ChequeValueDollars,
                    ChequeValueCents = cheque.ChequeValueCents
                }
            });
        }
        
    }
    
}

BankCheque/Views/Cheque/ChequeDataCollection.cshtml
@using BankCheque.Models.Cheque
@model ChequeVM

@section PageHeader {
    <h1>@Model.PageTitle</h1>
}

<div class="component cheque-data-collection">    
    @using (Html.BeginForm("SubmitCheque", "Cheque", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <fieldset>
            <legend>
                @Model.HelpMessage
            </legend>
            <div class="row">
                <div class="text-wrapper col-md-4 col-sm-12">@Model.PayeeNameLabel</div>
                <div class="input-wrapper col-md-8 col-sm-12">
                    <input id="cheque-payee-name" required pattern="[a-zA-Z ]*[a-zA-Z]+[a-zA-Z ]*" name="PayeeName" class="text-input" placeholder="Full Name"/>
                </div>
            </div>
            <div class="row">
                <div class="text-wrapper col-md-4 col-sm-12">@Model.ChequeValueLabel</div>
                <div class="input-wrapper col-md-5 col-sm-12">
                    <input id="cheque-dollars-value" required pattern="[0-9]{0,15}" name="ChequeValueDollars" class="text-input" placeholder="Dollars"/>
                </div>
                <div class="text-wrapper dot col-md-1">.</div>
                <div class="input-wrapper col-md-2 col-sm-12">
                    <input id="cheque-cents-value" pattern="[0-9]{0,2}" name="ChequeValueCents" class="text-input" placeholder="Cents" />
                </div>
            </div>
            <div class="row"> 
                <div class="col-md-4 col-sm-12"></div>
                <div class="btn-input-wrapper input-wrapper col-md-8 col-sm-12">
                    <input type="submit" value="Submit" class="btn-input" />
                </div>
            </div>   
        </fieldset>
    }
</div>

@Scripts.Render("~/script/chequescript")

BankCheque/Views/Cheque/SubmittedCheque.cshtml
@using BankCheque.Models.Cheque
@model ChequeVM

@section PageHeader {
    <h1>@Model.PageTitle</h1>
}

<div class="component cheque">    
    <div class="text-wrapper">@Model.ChequeData.PayeeName</div>
    <div class="text-wrapper">@Model.ChequeData.GetFormatedValue()</div>
    <div class="flex-text-wrapper">@Model.ChequeData.getValueInWords()</div>
</div>

BankCheque/Views/Shared/Footer.cshtml
<div class="footer">

</div>

BankCheque/Views/Shared/GlobalHeader.cshtml
<div class="global-header">

</div>

BankCheque/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    @Styles.Render("~/style/css")

</head>
<body>
    <div class="body-container">
        <div class="global-header">
            @Html.Partial("~/Views/Shared/GlobalHeader.cshtml")
        </div>
        <div class="page-header">
            @RenderSection("PageHeader")
        </div>

        @RenderBody()
        <div class="footer-container">
            @Html.Partial("~/Views/Shared/Footer.cshtml")
        </div>
    </div>
    @Scripts.Render("~/script/jquery")
    @Scripts.Render("~/script/bootstrap")
</body>
</html>